version: '3.8'

services:
  web:
    build: ./frontend/
    container_name: ras_guidance_frontend
    networks:
      - homelab_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.doc_annotation_app.rule=Host(`kea-doc-annotation.${SERVER_URL}`)"
      - "traefik.docker.network=homelab_network"

  server:
    build: ./
    container_name: ras_guidance_backend
    networks: 
      - homelab_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.doc_annotation_backend.rule=Host(`kea-doc-annotation-backend.${SERVER_URL}`)"
      - "traefik.docker.network=homelab_network"

networks:
  homelab_network:
    external: true
